export const PURCHASE_PENDING = "PURCHASE_PENDING";
export const PURCHASE_SUCCESS = "PURCHASE_SUCCESS";
export const PURCHASE_ERROR = "PURCHASE_ERROR";
export const UPDATE_PURCHASE_DIALOG = "SHOW_PURCHASE_DIALOG";
export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const PASSWORD_RESET_PENDING = "PASSWORD_RESET_PENDING";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_ERROR = "PASSWORD_RESET_ERROR";
export const LOGOUT = "LOGOUT";
export const TOKEN_VERIFICATION_PENDING = "TOKEN_VERIFICATION_PENDING";
export const TOKEN_VERIFICATION_SUCCESS = "TOKEN_VERIFICATION_SUCCESS";
export const TOKEN_VERIFICATION_ERROR = "TOKEN_VERIFICATION_ERROR";
export const ITEMS_PENDING = "ITEMS_PENDING";
export const ITEMS_SUCCESS = "ITEMS_SUCCESS";
export const ITEMS_ERROR = "ITEMS_ERROR";

